version: "3.9"
services:
  sync-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ${DATA_PATH:-.}
        target: /data
    environment:
      - BROWSE_ROOT=/data
      - PORT=8000
